version: 1
formatters:
  base_formatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: base_formatter
    stream: ext://sys.stdout
loggers:
  SleepInferenceLogger:
    level: INFO
    handlers: [console]
    propagate: no
disable_existing_loggers: False